all: 
	wbgen2 -f latex -D wrsw_endpoint.tex wbgen/ep_wishbone_controller.wb
	wbgen2 -f latex -D i2c_master.tex wbgen/i2c_master.wb
	wbgen2 -f latex -D wrsw_endpoint_mdio.tex wbgen/pcs_regs.wb
	wbgen2 -f latex -D wr_pps_gen.tex wbgen/pps_gen_wb.wb
	wbgen2 -f latex -D wb_simple_uart.tex wbgen/simple_uart_wb.wb
	wbgen2 -f latex -D wb_gpio.tex wbgen/wb_gpio.wb
	wbgen2 -f latex -D wb_vic.tex wbgen/wb_slave_vic.wb
	wbgen2 -f latex -D wrsw_nic.tex wbgen/wr_nic.wb
	wbgen2 -f latex -D wrsw_pstats.tex wbgen/wrsw_pstats.wb
	wbgen2 -f latex -D wrsw_rtu.tex wbgen/wrsw_rtu.wb
	wbgen2 -f latex -D wrsw_txtsu.tex wbgen/wrsw_txtsu.wb
	wbgen2 -f latex -D wrsw_tru.tex wbgen/tru_wishbone_slave.wb
	wbgen2 -f latex -D wrsw_tatsu.tex wbgen/tatsu_wishbone_controller.wb
	wbgen2 -f latex -D wb_simple_pwm.tex wbgen/simple_pwm_wb.wb
	wbgen2 -f latex -D wrsw_hwiu.tex wbgen/wrsw_hwiu.wb
